FROM python:3.9-slim

WORKDIR /app

# Install dependencies
COPY ./app/requirements.txt /app
RUN pip install --no-cache-dir -r /app/requirements.txt

# Copy chat server code
COPY ./server/chat_handover_server.py /app/chat_handover_server.py

# Copy chat server code
COPY ./app/ /app/

# Expose WebSocket port
EXPOSE 8765

# Command to run the chat server
CMD ["python", "chat_handover_server.py"]
